"""create project table

Revision ID: 74527f8c96af
Revises: 579801a75e4c
Create Date: 2025-12-10 22:23:41.030408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74527f8c96af'
down_revision: Union[str, Sequence[str], None] = '579801a75e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
